[package]
name = "mentat_query_translator"
version = "0.0.1"
workspace = ".."

[dependencies]
[dependencies.mentat_core]
path = "../core"

[dependencies.mentat_db]
path = "../db"

[dependencies.mentat_sql]
path = "../sql"

[dependencies.mentat_query]
path = "../query"

[dependencies.mentat_query_algebrizer]
path = "../query-algebrizer"

# Only for tests.
[dev-dependencies.mentat_query_parser]
path = "../query-parser"

[dependencies.mentat_query_projector]
path = "../query-projector"

[dependencies.mentat_query_sql]
path = "../query-sql"
