language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose -p edn
  - cargo test --verbose -p mentat_query
  - cargo test --verbose -p mentat_query_parser
  - cargo test --verbose -p mentat_tx_parser
