[package]
authors = [
  "Richard Newman <rnewman@twinql.com>",
  "Nicholas Alexander <nalexander@mozilla.com>",
  "Victor Porof <vporof@mozilla.com>",
  "Jordan Santell <jsantell@mozilla.com>",
  "Joe Walker <jwalker@mozilla.com>",
]
name = "mentat"
version = "0.4.0"
build = "build/version.rs"

[workspace]
members = []

[build-dependencies]
rustc_version = "0.1.7"

[dependencies]
chrono = "0.3"
error-chain = "0.8.1"
time = "0.1"

[dependencies.rusqlite]
version = "0.11"
# System sqlite might be very old.
features = ["bundled", "limits"]

[dependencies.edn]
path = "edn"

[dependencies.mentat_parser_utils]
path = "parser-utils"

[dependencies.mentat_core]
path = "core"

[dependencies.mentat_sql]
path = "sql"

[dependencies.mentat_db]
path = "db"

[dependencies.mentat_query]
path = "query"

[dependencies.mentat_query_algebrizer]
path = "query-algebrizer"

[dependencies.mentat_query_parser]
path = "query-parser"

[dependencies.mentat_query_projector]
path = "query-projector"

[dependencies.mentat_query_sql]
path = "query-sql"

[dependencies.mentat_query_translator]
path = "query-translator"

[dependencies.mentat_tx_parser]
path = "tx-parser"
