[package]
name = "mentat"
version = "0.4.0"
authors = ["Richard Newman <rnewman@twinql.com>", "Nicholas Alexander <nalexander@mozilla.com>"]

[dependencies]
clap = "2.19.3"
nickel = "0.9.0"
rusqlite = "0.8.0"

[dependencies.edn]
  path = "edn"

[dependencies.mentat_query]
  path = "query"

[dependencies.mentat_query_parser]
  path = "query-parser"

[dependencies.mentat_tx_parser]
  path = "tx-parser"
