[package]
name = "mentat_core"
version = "0.0.1"
workspace = ".."

[dependencies]
enum-set = { git = "https://github.com/rnewman/enum-set" }
lazy_static = "0.2"
num = "0.1"
ordered-float = "0.5"
uuid = "0.5"

[dependencies.edn]
path = "../edn"
