[package]
name = "query_pull_traits"
version = "0.0.1"
workspace = ".."

[lib]
name = "query_pull_traits"
path = "lib.rs"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dependencies.core_traits]
path = "../core-traits"

[dependencies.db_traits]
path = "../db-traits"
