[package]
name = "mentat_parser_utils"
version = "0.1.0"
authors = ["Victor Porof <vporof@mozilla.com>", "Richard Newman <rnewman@mozilla.com>"]

[dependencies]
combine = "2.1.1"

[dependencies.edn]
  path = "../edn"

[dependencies.mentat_query]
  path = "../query"
